"""empty message

Revision ID: 8441777e217a
Revises: 6d7bcb0cf9fa
Create Date: 2018-04-28 15:33:40.908285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8441777e217a'
down_revision = '6d7bcb0cf9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
